name: toy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - ipykernel
  - tqdm
  - dcor
  - pytorch
  - torchvision
  - colordict
  - tabulate
  - scikit-image
  - pygraphviz
  - python-slugify
